# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9122ef8264a655a751baa8a8374c7a5c4c1e898526bc63ea80392e4ed266ce2178a4f675a8ccb9658e54fd7a72be8b27c9291af0f750360394c71208654963f

test:
  secret_key_base: c06882dbea4028154e305dc3e06bad032e9e5b6a84865a03733ad2e2a328f0a0f0b06d878186823783c20ade32eb2536f436457f9fea83641f4e0a659f82789b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
